### PR TITLE
Update usb_modeswitch to version 2.2.5

### PR DESCRIPTION
**Pull request by vblack**
Signed-off-by: Kostiantyn Luzan vblack2006@gmail.com

### CODE REVIEW

**Comment by jamesgol** [comment]
This should be in its own new repository

**Comment by jamesgol** [comment]
Also I don't want to include binaries without source if possible.   This
should be built as part of the process

**Comment by vblack** [comment]
Ok, no problem, I will prepare sources in new repository.

**Comment by jamesgol** [comment]
I created a new repository for it here: https://github.com/Nu3001/external_usb_modeswitch

The manifest will need to be changed also

**Pull request closed without merging**
